#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
{%- if cookiecutter.use_async == 'y' %}
exec /usr/local/bin/gunicorn _config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn_worker.UvicornWorker
{%- else %}
exec /usr/local/bin/gunicorn _config.wsgi --bind 0.0.0.0:5000 --chdir=/app
{%- endif %}
