release: python manage.py migrate
{%- if cookiecutter.use_async == "y" %}
web: gunicorn _config.asgi:application -k uvicorn_worker.UvicornWorker
{%- else %}
web: gunicorn _config.wsgi:application
{%- endif %}
{%- if cookiecutter.use_celery == "y" %}
worker: REMAP_SIGTERM=SIGQUIT celery -A _config.celery_app worker --loglevel=info
beat: REMAP_SIGTERM=SIGQUIT celery -A _config.celery_app beat --loglevel=info
{%- endif %}
